Add --echo, --offset and --limit MODSI-32
folio-org/mod-shared-index pull request #25
Opened 2022-04-08 13:55 UTC by skoczko

Add --echo, --offset and --limit. Minor cleanup.

2022-04-08 14:48 UTC, adamdickmeiss commented on client/src/main/java/org/folio/shared/index/client/Client.java
> +      Future.<Void>future(x -> sendMarcXmlChunk(stream, promise));
```suggestion
      sendMarcXmlChunk(stream, promise);
```

2022-04-08 15:33 UTC, skoczko commented on client/src/main/java/org/folio/shared/index/client/Client.java
> +import static java.lang.System.out;
Generally, yes but for help and logging records it looks pretty bad. But I don't mind..

2022-04-08 15:34 UTC, adamdickmeiss commented on client/src/main/java/org/folio/shared/index/client/Client.java
> +      return;
Why?

2022-04-09 12:01 UTC, adamdickmeiss requested changes
Extra semicon in one place.. OK with system println , but then let's make SQ shut up by adding 


    @java.lang.SuppressWarnings({"squid:S106"})  // using standard output on purpose

2022-04-10 09:59 UTC, skoczko commented
@adamdickmeiss I am little confused about the coverage -- I bumped it up to 100% but after refactoring the ReaderProxy it came down -- I would assume the code get exercised the same way, no?

2022-04-10 12:11 UTC, skoczko commented
@adamdickmeiss anyway, should I go ahead and merge?

2022-04-10 12:18 UTC, adamdickmeiss approved these changes

2022-04-10 13:03 UTC, merged