MODSI-8, database design, add match_point table.
folio-org/mod-shared-index pull request #6
Opened 2022-03-06 22:40 UTC by nielserik

The PR implements a change to the table structure of the shared index - from having one table, BIB_RECORD, with a fixed number of match value columns, to a normalized, two-table structure, which still has a BIB_RECORD table, but now without any match value columns, and then a MATCH_POINT table to hold those match values instead:

MATCH_POINT
   (BIB_RECORD_ID,
    MATCH_TYPE_ID,
    MATCH_VALUE)

This change is necessary primarily because it allows for an unlimited number of match values of a given type per bib record, for example an unbounded number of ISBNs per bib record, and secondly because it allows for an unbounded number of different match types (defined by match_type_id) with no need to add additional columns to BIB_RECORD for each new match type that we might want to add later.

The change in database structure does not affect the APIs for ingestion or retrieval. It does of course require internal changes to the API implementations, in order to populate and query the table structure.  So in this PR, ingestion is implemented by a trigger on BIB_RECORD that invokes a stored function to update MATCH_POINT in case of inserts or updates to BIB_RECORD (deletion of records in BIB_RECORD are simply cascaded to MATCH_POINT and are thus not part of the stored function). The trigger approach is simple in this case, because the MATCH_POINT table is entirely dependent on the BIB_RECORD table. This implementation will work but it is for proof of concept (that the APIs don't need to change), meaning that, if desired, the ingestion logic could be implemented in Vert.X instead. 

As for batch updates and transactions, this implementation means, that BIB_RECORD can be updated in batch or with longer transactions spanning multiple insert, update or delete operations on BIB_RECORD. The subsequent, "inline" updates to MATCH_POINT would be part of those transactions and be committed and rolled back with them. 

The tables are not meant to be complete and several details, like the use of identifiers for match-types etc, are preliminary. They are merely chosen to be able to use 'inventory' JSON schema that we have at hand from the old SI.

2022-03-07 12:53 UTC, skoczko requested changes

2022-03-07 12:53 UTC, skoczko commented on src/main/java/org/folio/reshare/index/storage/Storage.java
> +            "CREATE OR REPLACE FUNCTION " + matchPointFunction
Let's avoid hard-coding any specific match key methods here. These should be "pluggable" so let's factor them out to a separate class or classes.

2022-03-07 12:53 UTC, skoczko commented on src/main/java/org/folio/reshare/index/storage/Storage.java
> +    this.matchTypeTable = pool.getSchema() + ".match_type";
We should align table names with the OpenAPI spec:

* `match_type` -> `MATCH_KEY_CONFIGS`
* `match_point` -> `MATCH_KEY_VALUES`

would be one way. But we can also go the other way and align the OpenAPI spec. @adamdickmeiss @nielserik preferences?

2022-03-07 12:53 UTC, skoczko commented on src/main/java/org/folio/reshare/index/storage/Storage.java
> +  private static final String IDENTIFIER_TYPE_ID_ISBN = "8261054f-be78-422d-bd51-4ed9f33c3422";
These constants should be factored out to individual match key method implementation classes.

2022-03-07 15:38 UTC, adamdickmeiss commented on src/main/java/org/folio/reshare/index/storage/Storage.java
> +                + "   END IF;"
I'm not much fund of triggers or SQL functions.. 1: I don't understand it (:-) .. 2: They are difficult to unit test.. 3. I think parsing of JSON should be done in Java code and knowledge about UUIDs in inventory should definitely not live in an SQL function.. 4: upgrading problems with triggers/functions.. 

So if the logic is "universal", a trigger MAY be good.. But I don't think in this case, that applies..

2022-03-07 21:41 UTC, nielserik commented
The only thing that matters in this PR is the table structure. 

How tables and columns are named, and with what coding languages the population of the tables is implemented is secondary. 

So if it provides clarity to have other names for database elements or the API schema elements, that's totally fine. 

The PR does not suggest that ingestion should be implemented with stored functions, on the contrary. As pointed out in the description: "This implementation will work but it is for proof of concept (...) if desired, the ingestion logic could be implemented in Vert.X instead."  Writing 20 lines of plpgsql code just happened to be the quickest way to implement a demo of it. It could be any other language or framework of your choice of course.   

Also, please note that the Inventory UUID is only present in this PoC to make it work with the test data we have at hand (from the ReShare harvest jobs). Those data happen to be FOLIO Inventory data so the code must pick ISBN numbers by the identifier UUID of ISBNs in Inventory, that's all. In the end -- I would expect -- no Inventory UUIDs or codes should live in the code of mod-shared-index. 

Once a schema is established for that incoming JSON (and I would not expect that to be an Inventory schema), the ingestion code will need to implement its own way of finding the ISBNs in the object. Perhaps the ISBNs will arrive as a JSON array of ISBN values in that JSON, which would greatly simply find that parse. 

What matters is, that the values end up in the table MATCH_POINT,  aka MATCH_KEY_VALUES, using logic equivalent to what is demonstrated in the "match_points()" function.

2022-03-07 22:28 UTC, nielserik commented
The table structure is important because it essential for fast and flexible retrieval of clusters of holdings. Perhaps it would be helpful to go through some examples of retrieval logic.

2022-03-08 11:24 UTC, adamdickmeiss approved these changes
I don't mind this merged now. The match key must be computed client side obviously later.

2022-03-08 12:03 UTC, closed without merging